name: Build Docker Images

on: push

jobs:
  android-qt:
    name: "cmake android qt"
    strategy:
      fail-fast: false
      matrix:
        include:
          - android_build_tools: 31.0.0
            android_compile_sdk: 31
            android_sdk_version: 7583922
            gradle_version: 7.2
            ndk_version: 22.1.7171670
            qt_version: 6.2.2
            qt_modules: ""
            qt_arch: android_x86

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to github 
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build and publish docker container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.docker_file }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/fettpet/docker_qt_android:qt${{ matrix.qt_version }}-android_sdk${{ matrix.ANDROID_SDK_VERSION }}
          build-args: |
            ANDROID_SDK_VERSION=${{ matrix.android_sdk_version }}
            QT_VERSION=${{ matrix.qt_version }}
            QT_MODULES=${{ matrix.qt_modules }}
            QT_ARCH=${{ matrix.qt_arch }}
            GRADLE_VERSION=${{ matrix.gradle_version }}
            ANDROID_COMPILE_SDK=${{ matrix.android_compile_sdk }}
            ANDROID_BUILD_TOOLS=${{ matrix.android_build_tools }}
            NDK_VERSION=${{ matrix.ndk_version }}
